# Generated by Django 5.1 on 2024-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_upload',
            field=models.FileField(default=1, upload_to='uploads/', verbose_name='PDF'),
        ),
    ]
